export const GALLERY_API_SERVICE_PATH = '/gallery/service'

const GALLERY_API_SERVICE_PROTOCOL='http://'
const GALLERY_API_SERVICE_HOST='localhost:8080'
export const GALLERY_API_ROOT_URL=`${GALLERY_API_SERVICE_PROTOCOL}${GALLERY_API_SERVICE_HOST}`
export const GALLERY_API_LOGIN_URL=`${GALLERY_API_SERVICE_PROTOCOL}${GALLERY_API_SERVICE_HOST}/gallery/login`
export const GALLERY_API_USER_URL=`${GALLERY_API_SERVICE_PROTOCOL}${GALLERY_API_SERVICE_HOST}/gallery/user`
export const GALLERY_API_IMAGE_ROOT_URL=`${GALLERY_API_SERVICE_PROTOCOL}${GALLERY_API_SERVICE_HOST}`

export const IMAGE_FORMAT_THUMBNAIL = 'thumb'
